import {
    ACCOUNTS,
    CONFIRM_SEED,
    CREATE_DERIVED_ACCOUNT,
    CREATE_WALLET,
    DASHBOARD,
    IMPORT_WALLET,
    SEND,
    SHOW_SEED,
    SUPPORT,
    WELCOME,
    WELCOME_BACK,
} from './route-names';

export {
    ACCOUNTS,
    CONFIRM_SEED,
    CREATE_DERIVED_ACCOUNT,
    CREATE_WALLET,
    DASHBOARD,
    IMPORT_WALLET,
    SEND,
    SHOW_SEED,
    SUPPORT,
    WELCOME,
    WELCOME_BACK,
};
